name 'puppet-pgconf'
version '0.1.0'
source 'https://github.com/camptocamp/puppet-pgconf.git'
author 'camptocamp'
license 'Apache'
summary 'Manage postgresql.conf entries'
description 'A defined type to manage entries in Postgresql's configuration file'
project_page 'https://github.com/camptocamp/puppet-pgconf'
